version: '4'
services:
  inventory_mysql:
    image: mysql:8.3.0
    container_name: inventory_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - inventory_mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  inventory_mysql_data:
